openapi: "3.0.1"
info:
  title: 'Supply Chain API'
  version: "1"
servers:
  - url: "https://ev5uwiczj6.execute-api.eu-central-1.amazonaws.com/{basePath}"
    variables:
      basePath:
        default: "test"
paths:
  /supply-chain:
    get:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Products"
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
          required: true
      responses:
        "201":
          description: "201 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"

  /supply-chain/{id}:
    get:
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"

    delete:
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
          type: "string"
      responses:
        "204":
          description: "204 - No content"

components:
  schemas:
    Products:
      title: "List of products"
      type: "array"
      items:
        $ref: "#/components/schemas/Product"
    Product:
      title: "Product Schema"
      type: "object"
      properties:
        id:
          description: Product identifier
          type: string
        name:
          description: Product name
          type: string
        price:
          description: Price
          type: number
        quantity:
          description: Quantity
          type: integer
